site_name: DevOps Foundation Roadmap
site_description: Complete DevOps learning roadmap - From Beginner to Expert. Master DevOps fundamentals, CI/CD, containers, automation, and cloud technologies with practical Arabic resources and industry best practices.
site_author: Mujahed Altahleh
site_url: https://mtahle.github.io/DevOps-Foundation-Roadmap

# Repository
repo_name: mtahle/DevOps-Foundation-Roadmap
repo_url: https://github.com/mtahle/DevOps-Foundation-Roadmap
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  language: en
  logo: assets/logo.svg
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: cyan
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - content.tooltips
    - toc.follow
    - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: mtahle
      repo: DevOps-Foundation-Roadmap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
      lang: 
        - en
        - ar
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      timezone: UTC
      locale: en
      fallback_to_build_date: true
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true
        remove_empty_space: true
      cache_safe: true

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mtml-chtml.js
  - https://cdn.jsdelivr.net/npm/mermaid@11.4.0/dist/mermaid.min.js
  - javascripts/mermaid.js

# Extra
extra:
  version:
    provider: mike
    default: latest
  revision_date: !ENV [CI_COMMIT_TIMESTAMP, REVISION_DATE]
  last_updated: !ENV [BUILD_DATE, 2025-09-21]
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtahle
      name: GitHub Repository
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mtahle
      name: Twitter Profile
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mtahle
      name: LinkedIn Profile
    - icon: fontawesome/solid/podcast
      link: https://open.spotify.com/show/24UfF6aMe0AyUIJeckaEf7
      name: DevOps Podcast
  status:
    new: Recently added
    deprecated: Deprecated
  meta:
    - name: keywords
      content: "DevOps, Arabic DevOps, DevOps Tutorial, CI/CD, Docker, Kubernetes, Cloud, Infrastructure, Automation, DevOps Learning, Arabic Tech, مهندس DevOps"
    - name: author
      content: "Mujahed Al Tahleh"
    - name: robots
      content: "index, follow"
    - name: googlebot
      content: "index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1"
    - property: "og:type"
      content: "website"
    - property: "og:title"
      content: "DevOps Foundation Roadmap - Complete Learning Guide"
    - property: "og:description"
      content: "Comprehensive DevOps learning roadmap from beginner to expert. Includes practical tutorials, Arabic podcast resources, and industry best practices."
    - property: "og:image"
      content: "https://mtahle.github.io/DevOps-Foundation-Roadmap/assets/logo-colored.svg"
    - property: "og:url"
      content: "https://mtahle.github.io/DevOps-Foundation-Roadmap/"
    - property: "og:site_name"
      content: "DevOps Foundation Roadmap"
    - name: "twitter:card"
      content: "summary_large_image"
    - name: "twitter:title"
      content: "DevOps Foundation Roadmap - Complete Learning Guide"
    - name: "twitter:description"
      content: "Master DevOps from basics to advanced. Practical roadmap with Arabic resources."
    - name: "twitter:image"
      content: "https://mtahle.github.io/DevOps-Foundation-Roadmap/assets/logo-colored.svg"
    - name: "twitter:creator"
      content: "@mtahle"

# Navigation
nav:
  - Home: index.md
  - Fundamentals:
    - concepts/index.md
    - Internet Basics: concepts/internet-basics.md
    - Web Development: concepts/web-development.md
    - Domains & DNS: concepts/domains-dns.md
    - Internet Protocols: concepts/protocols.md
    - SSL/TLS: concepts/ssl.md
    - Web Hosting: concepts/hosting.md
  - Linux & Systems:
    - linux/index.md
    - Linux Introduction: linux/introduction.md
    - Web Hosting: linux/web-hosting.md
    - Advanced Hosting: linux/advanced-hosting.md
    - Troubleshooting Tools: linux/troubleshooting-tools.md
  - Containers & Orchestration:
    - containers/index.md
    - Container Introduction: containers/introduction.md
    - Container Security: containers/security.md
    - Kubernetes Production: containers/kubernetes-production.md
  - Automation & CI/CD:
    - automation/index.md
    - Automation Introduction: automation/introduction.md
    - Container CI/CD: automation/container-cicd.md
  - Monitoring & Observability:
    - monitoring/index.md
    - Monitoring Introduction: monitoring/introduction.md
  - Resources & References:
    - resources/index.md
    - Podcasts: resources/podcast.md

# Copyright
copyright: Copyright &copy; 2025 Mujahed Altahleh