site_name: DevOps Foundation Roadmap
site_description: Complete DevOps learning roadmap - From Beginner to Expert
site_author: Mujahed Altahleh
site_url: https://mtahle.github.io/DevOps-Foundation-Roadmap

# Repository
repo_name: mtahle/DevOps-Foundation-Roadmap
repo_url: https://github.com/mtahle/DevOps-Foundation-Roadmap
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: blue
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - toc.follow
    - toc.integrate

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: mtahle
      repo: DevOps-Foundation-Roadmap
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mtahle
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mtahle
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/mtahle

# Page tree
nav:
  - الرئيسية: index.md
  - المفاهيم الأساسية:
    - concepts/index.md
    - نظرة عامة على الـ DevOps: concepts/overview.md
    - الثقافة والممارسات: concepts/culture.md
    - دورة حياة التطوير: concepts/lifecycle.md
  - لينكس والأساسيات:
    - linux/index.md
    - مقدمة في لينكس: linux/introduction.md
    - سطر الأوامر: linux/command-line.md
    - إدارة النظام: linux/system-admin.md
    - الشبكات: linux/networking.md
    - الأمان: linux/security.md
  - الحاويات والتنسيق:
    - containers/index.md
    - مقدمة في الحاويات: containers/introduction.md
    - Docker المتقدم: containers/advanced-docker.md
    - Kubernetes: containers/kubernetes.md
    - أمان الحاويات: containers/security.md
    - المراقبة: containers/monitoring.md
  - الأتمتة والنشر:
    - automation/index.md
    - مقدمة في CI/CD: automation/cicd.md
    - Jenkins: automation/jenkins.md
    - GitHub Actions: automation/github-actions.md
    - GitLab CI: automation/gitlab-ci.md
    - Infrastructure as Code: automation/iac.md
  - المراقبة والملاحظة:
    - monitoring/index.md
    - أساسيات المراقبة: monitoring/fundamentals.md
    - Prometheus و Grafana: monitoring/prometheus-grafana.md
    - تجميع السجلات: monitoring/logging.md
    - التتبع الموزع: monitoring/tracing.md
  - الموارد والمراجع:
    - resources/index.md
    - الكتب المفيدة: resources/books.md
    - الدورات التدريبية: resources/courses.md
    - المدونات والمواقع: resources/blogs.md
    - الشهادات: resources/certifications.md

# Copyright
copyright: Copyright &copy; 2023 محمد طحلة
